[build]
  command = "yarn download-s3 && yarn build"
  publish = "out"

[context.production]
  environment = { NODE_VERSION = "18.18.2" }

[context.deploy-preview]
  environment = { NODE_VERSION = "18.18.2" }

[context.branch-deploy]
  environment = { NODE_VERSION = "18.18.2" }

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404