version: 2.1

orbs:
  aws-s3: circleci/aws-s3@2.0.0
  aws-cloudfront: topmonks/aws-cloudfront@1.0.0

jobs:
    build:
        working_directory: ~/letters
        docker:
          - image: cimg/node:14.16.0
        steps:
            - checkout
            - restore_cache:
                name: Restore Yarn Package Cache
                keys:
                    - yarn-packages-{{ checksum "yarn.lock" }}
            - run:
                name: Install Dependencies
                command: yarn install --immutable
            - save_cache:
                name: Save Yarn Package Cache
                key: yarn-packages-{{ checksum "yarn.lock" }}
                paths:
                    - ~/.cache/yarn
            - run:
                name: Build Static Site
                command: yarn download-s3 && yarn build && yarn export
            - persist_to_workspace:
                root: ~/letters
                paths:
                    - .
    deploy:
        working_directory: ~/letters
        docker:
          - image: cimg/node:14.16.0
        steps:
            - attach_workspace:
                at: ~/letters
            - aws-s3/sync:
                arguments: --delete
                from: out
                to: '${UTL_S3_BUCKET}'
            - aws-cloudfront/invalidate:
                distribution_id: '${UTL_DISTRIBUTION_ID}'
                paths: '/*'

workflows:
    version: 2
    build-deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only: main
