version: 2.1

orbs:
    aws-cli: circleci/aws-cli@2.0.2

jobs:
    build:
        working_directory: ~/letters
        docker:
          - image: cimg/node:14.16.0
        steps:
            - checkout
            - restore_cache:
                name: Restore Yarn/Node Cache
                keys:
                    - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
                    - yarn-packages-v1-{{ .Branch }}-
                    - yarn-packages-v1-
            - run:
                name: Install Dependencies
                command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
            - save_cache:
                name: Save Yarn/Node Cache
                key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
                paths:
                    - ~/.cache/yarn
                    - node_modules
            - run:
                name: Build Static Site
                command: yarn download-s3 && yarn build && yarn export
            - persist_to_workspace:
                root: ~/letters
                paths:
                    - out
    deploy:
        working_directory: ~/letters
        docker:
          - image: cimg/node:14.16.0
        steps:
            - attach_workspace:
                at: ~/letters
            - aws-cli/setup
            - run:
                name: AWS S3 Sync
                command: aws s3 sync out ${UTL_S3_BUCKET} --delete
            - run:
                name: AWS CloudFront Invalidation
                command: aws cloudfront create-invalidation --distribution-id ${UTL_DISTRIBUTION_ID} --paths '/*'

workflows:
    version: 2
    build-deploy:
        jobs:
            - build
            - deploy:
                context: aws
                requires:
                    - build
                filters:
                    branches:
                        only: main
